export const mockReminders = [
  {
    id: 1,
    contact_id: "c1",
    label: "Call Mom",
    day: 15,
    month: 3,
    year: 2025,
    type: "recurring_year",
    frequency_number: null,
    calendar_type: "gregorian",
    original_day: null,
    original_month: null,
    original_year: null,
    last_triggered_at: null,
    number_times_triggered: 0,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
  {
    id: 2,
    contact_id: "c1",
    label: "Lunar Bday",
    day: 12,
    month: 2,
    year: 2025,
    type: "recurring_year",
    frequency_number: null,
    calendar_type: "lunar",
    original_day: 15,
    original_month: 1,
    original_year: 2025,
    last_triggered_at: null,
    number_times_triggered: 0,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
  },
] as const;
